// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OE.Module.LHB.Shared.Models;

[Table("Address")]
public partial class Address
{
    [Key]
    public int AddressId { get; set; }

    [StringLength(120)]
    public string Address1 { get; set; }

    [StringLength(120)]
    public string Address2 { get; set; }

    [StringLength(120)]
    public string Address3 { get; set; }

    [StringLength(100)]
    public string City { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string State { get; set; }

    [StringLength(16)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string Geocoding { get; set; }

    public float? Longitude { get; set; }

    public float? Latitude { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [Column("l10N")]
    [StringLength(4000)]
    public string L10N { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [Required]
    [StringLength(256)]
    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    [Required]
    [StringLength(256)]
    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }
}