// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OE.Module.LHB.Shared.Models;

[Table("Attribute")]
public partial class Attribute
{
    [Key]
    public int AttributeId { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public int? ParentAttributeId { get; set; }

    [Column("l10N")]
    [StringLength(4000)]
    public string L10N { get; set; }

    [Required]
    [StringLength(256)]
    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    [Required]
    [StringLength(256)]
    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    [InverseProperty("Attribute")]
    public virtual ICollection<ProviderAttribute> ProviderAttributes { get; set; } = new List<ProviderAttribute>();
}